# Generated by Django 5.1.6 on 2025-07-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='report_photos/')),
                ('status', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
