# Generated by Django 5.1.6 on 2025-07-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, default='report_photos/default.jpg', null=True, upload_to='report_photos/'),
        ),
    ]
